name: Develop Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Cache Poetry and Dependencies
      id: cache-poetry
      uses: actions/cache@v4
      with:
          path: |
            ~/.cache/pypoetry
            ~/.poetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

    - name: Install Poetry
      run: |
        if [ ! -d "$HOME/.poetry" ]; then
          curl -sSL https://install.python-poetry.org | python3 -
        fi
        export PATH="$HOME/.local/bin:$PATH"
        
    - name: Install dependencies
      run: |
        poetry install --no-root

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
    
      - name: Restore Poetry from Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry
            ~/.poetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Add Poetry to PATH
        run: export PATH="$HOME/.local/bin:$PATH"
  
      - name: Run linter
        run: poetry run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
    
      - name: Restore Poetry from Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.poetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
  
      - name: Add Poetry to PATH
        run: export PATH="$HOME/.local/bin:$PATH"

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Deploy
      if: success()
      run: |
        echo "Deploying the application..."