name: Develop Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        
    - name: Install dependencies
      run: |
        poetry install

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Run linter
      run: poetry run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Run tests
      run: poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Deploy
      if: success()
      run: |
        echo "Deploying the application..."