name: Develop Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Cache Poetry
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    
    - name: Install Poetry
      run: pipx install poetry
    
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: .venv
        key: pydeps-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
    
    - name: Install project
      run: poetry install --no-interaction

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Poetry and venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.local
            .venv
          key: ${{ runner.os }}-poetry-and-venv-${{ hashFiles('**/poetry.lock') }}
      
      - name: Run linter
        run: |
          poetry run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Poetry and venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.local
            .venv
          key: ${{ runner.os }}-poetry-and-venv-${{ hashFiles('**/poetry.lock') }}
      
      - name: Run tests
        run: |
          poetry run pytest .

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Deploy
      if: success()
      run: |
        echo "Deploying the application..."