name: Develop Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      poetry-cache-hit: ${{ steps.cache-poetry.outputs.cache-hit }}
      venv-cache-hit: ${{ steps.cache-venv.outputs.cache-hit }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    
    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ~/.poetry
        key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        $HOME/.poetry/bin/poetry install --no-interaction --no-root

    - name: Upload venv for reuse
      if: steps.cache-venv.outputs.cache-hit != 'true'
      uses: actions/upload-artifact@v3
      with:
        name: python-venv
        path: .venv

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Download venv
      if: needs.setup.outputs.venv-cache-hit != 'true'
      uses: actions/download-artifact@v3
      with:
        name: python-venv
    - run: |
        echo ".venv" >> $GITHUB_PATH
    
    - name: Run linter
      run: .venv/bin/flake8 .

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Download venv
      if: needs.setup.outputs.venv-cache-hit != 'true'
      uses: actions/download-artifact@v3
      with:
        name: python-venv
    - run: |
        echo ".venv" >> $GITHUB_PATH
    
    - name: Run tests
      run: .venv/bin/pytest .

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Deploy
      if: success()
      run: echo "Deploying the application..."
