name: Develop Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: reuse setup steps
      uses: ./.github/workflows/setup-python-env.yml
      with:
        python-version: '3.10'
    - name: Run linter
      run: ${{ env.POETRY_BIN }} run flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: reuse setup steps
        uses: ./.github/workflows/setup-python-env.yml
        with:
          python-version: '3.10'
      - name: Run tests
        run: ${{ env.POETRY_BIN }} run pytest .

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Deploy
      if: success()
      run: echo "Deploying the application..."
