name: Main Pipeline

on:
  push:
    branches: [ main ]

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linter
      run: flake8 .

    - name: Run tests
      run: pytest

    - name: Deploy
      run: |
        echo "Deploying the application..."