name: Main Pipeline

on:
  push:
    branches: [ main ]

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run linter
      run: flake8 .
    - name: Run tests
      run: pytest
    - name: Deploy
      run: |
        echo "Deploying the application..."